packages:
  - packages/*

blockExoticSubdeps: false

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  utf-8-validate: true
  vue-demi: true
