#!/usr/bin/with-contenv bash
# shellcheck disable=SC1008

printf '[cont-init.d] Creating folders if missing\n'

mkdir -p "$DEEMIX_MUSIC_DIR"
mkdir -p "$DEEMIX_DATA_DIR"

printf '[cont-init.d] Fixing folder permissions\n'

if [ -n "${DISABLE_OWNERSHIP_CHECK}" ] || [ -n "${DISABLE_OWNERSHIP_CHECK_MUSIC}" ] || x; then
	printf '[cont-init.d] Music folder ownership check disabled by environment variable\n'
else
	printf '[cont-init.d] Fixing music folder permissions\n'
	chown -R "$PUID":"$PGID" "$DEEMIX_MUSIC_DIR"
fi

if [ -n "${DISABLE_OWNERSHIP_CHECK}" ] || [ -n "${DISABLE_OWNERSHIP_CHECK_DATA}" ] || x; then
	printf '[cont-init.d] Data folder ownership check disabled by environment variable\n'
else
	printf '[cont-init.d] Fixing data folder permissions\n'
	chown -R "$PUID":"$PGID" "$DEEMIX_DATA_DIR"
fi

# Fix misconfigured download locations. The container's download map is always /downloads.
if [ -f "/config/config.json" ]; then
	jq '.downloadLocation = "/downloads"' /config/config.json >tmp.$$.json && mv tmp.$$.json /config/config.json
	chown "$PUID":"$PGID" /config/config.json
fi
