#!/usr/bin/with-contenv bash
# shellcheck disable=SC1008

printf '[cont-init.d] Creating Folders if Missing\n'

mkdir -p "$DEEMIX_MUSIC_DIR"
mkdir -p "$DEEMIX_DATA_DIR"

printf '[cont-init.d] Fixing Folder Permissions - Config Folder\n'

chown -R "$PUID":"$PGID" "$DEEMIX_MUSIC_DIR"

if [ -n "${DISABLE_OWNERSHIP_CHECK}" ]; then
	printf '[cont-init.d] Download Folder Ownership Check disabled by Environment Variable\n'
else
	printf '[cont-init.d] Fixing Folder Permissions - Downloads Folder\n'
	chown -R "$PUID":"$PGID" "$DEEMIX_DATA_DIR"
fi

# Fix misconfigured download locations. The container's download map is always /downloads.
if [ -f "/config/config.json" ]; then
	jq '.downloadLocation = "/downloads"' /config/config.json >tmp.$$.json && mv tmp.$$.json /config/config.json
	chown "$PUID":"$PGID" /config/config.json
fi
