name: Lint and Test

on:
  pull_request:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm -r --filter=deezer-js --filter=deemix build

      - run: pnpm lint

      # - run: pnpm test
